# This is useful for quickly accessing a terminal without leaving your current workspace.
# ~/.hammerspoon/vim-overlay.lua is using this configuration to create a terminal overlay for vim.
edge center-sized
kitty_conf overlay-nvim.conf
start_as_hidden yes
